import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";

import { db } from "@/database";
import { bills } from "@/database/schemas";
import { formatCurrency, formatDate } from "@/lib/utils";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export default async function PublicInvoicePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const bill = await db.query.bills.findFirst({ where: eq(bills.id, id), with: { items: true, customer: true, shop: true } });
  if (!bill?.shop) notFound();
  return <main className="mx-auto max-w-4xl px-4 py-8 sm:py-12"><Card><CardHeader className="gap-2 text-center"><CardTitle className="font-heading text-3xl">{bill.shop.name}</CardTitle><CardDescription>{bill.shop.address}{bill.shop.gstin && ` · GSTIN: ${bill.shop.gstin}`}</CardDescription></CardHeader><Separator /><CardContent className="flex flex-col gap-6 pt-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">Invoice</p><p className="font-mono font-medium">{bill.invoiceNumber}</p></div><div className="text-right"><p className="text-sm text-muted-foreground">Date</p><p className="font-medium">{formatDate(bill.billDate)}</p></div></div><div><p className="text-sm text-muted-foreground">Bill to</p><p className="font-medium">{bill.customer?.name ?? "Walk-in Customer"}</p>{bill.customer?.phone && <p className="font-mono text-sm text-muted-foreground">{bill.customer.phone}</p>}</div><Table><TableHeader><TableRow><TableHead>Item</TableHead><TableHead className="text-right">Qty</TableHead><TableHead className="text-right">GST</TableHead><TableHead className="text-right">Amount</TableHead></TableRow></TableHeader><TableBody>{bill.items.map((item) => <TableRow key={item.id}><TableCell><p className="font-medium">{item.productName}</p><p className="font-mono text-xs text-muted-foreground">{item.hsnCode ?? "No HSN"}</p></TableCell><TableCell className="text-right">{item.quantity} {item.unit}</TableCell><TableCell className="text-right">{item.gstRate}%</TableCell><TableCell className="text-right font-mono">{formatCurrency(item.lineTotalPaise)}</TableCell></TableRow>)}</TableBody></Table><div className="ml-auto flex w-full max-w-xs flex-col gap-2"><div className="flex justify-between text-sm"><span className="text-muted-foreground">Subtotal</span><span className="font-mono">{formatCurrency(bill.subtotalPaise)}</span></div><div className="flex justify-between text-sm"><span className="text-muted-foreground">GST</span><span className="font-mono">{formatCurrency(bill.gstTotalPaise)}</span></div>{bill.discountPaise > 0 && <div className="flex justify-between text-sm"><span className="text-muted-foreground">Discount</span><span className="font-mono">-{formatCurrency(bill.discountPaise)}</span></div>}<Separator /><div className="flex justify-between text-lg font-semibold"><span>Total</span><span className="font-mono">{formatCurrency(bill.totalPaise)}</span></div>{bill.amountDuePaise > 0 && <div className="flex justify-between text-sm"><span className="text-muted-foreground">Balance due</span><span className="font-mono">{formatCurrency(bill.amountDuePaise)}</span></div>}</div></CardContent><CardFooter className="justify-center text-sm text-muted-foreground">Thank you for your business.</CardFooter></Card></main>;
}
